version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fashionmnist-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: fashionmnist-frontend
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8000/predict
    depends_on:
      - backend